name: CI
on: [push]
jobs:
  test_build_run_push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run tests
        run :
          pip install pytest
          pytest
      - name: build docker image
        run:
          docker build -t valid_operation .
      - name: run docker image
        run:
          docker run valid_operation
      - name: docker login
        env:
          DOCKER_USER: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: docker tag
      
        run: docker tag valid_password:latest adamkh2/dockerhubOp:tagname
      - name: docker push
        run: docker push adamkh2/dockerhubOp:tagname